name: duit_hetu_extension
description: "
Hetu Script extension for the duit framework, allowing to execute dynamic scripts"
version: 1.0.0
homepage: https://github.com/Duit-Foundation/duit_hetu_extension

environment:
  sdk: '>=3.2.3 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  duit_kernel: ^2.0.1
  flutter:
    sdk: flutter
  hetu_script: ^0.4.2+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:

